#ifndef BAMT_ENGINE_SETTINGS
#define BAMT_ENGINE_SETTINGS

#define BAMT_WINDOW_NAME "BAMT ENGINE"

#define BAMT_REFERENCE_RESOLUTION_WIDTH 2000
#define BAMT_REFERENCE_RESOLUTION_HEIGHT 1200
#define BAMT_RENDERER_SCALE 100
#define BAMT_RESOLUTION_WIDTH 1280
#define BAMT_RESOLUTION_HEIGHT 720
#define BAMT_TARGET_FRAME_RATE 60

// PHYSICS
#define BAMT_PHYSICS_STEPS 10
#endif