#ifndef BAMT_ENGINE_SETTINGS
#define BAMT_ENGINE_SETTINGS

#define BAMT_WINDOW_NAME "BAMT ENGINE"
#define BAMT_RESOLUTION_WIDTH 1280
#define BAMT_RESOLUTION_HEIGHT 720
#define BAMT_TARGET_FRAME_RATE 60

// PHYSICS
#define BAMT_PHYSICS_STEPS 50
#endif