#ifndef BAMT_ENGINE_SETTINGS
#define BAMT_ENGINE_SETTINGS

#define BAMT_WINDOW_NAME "BAMT"

// SCALING
#define BAMT_REFERENCE_RESOLUTION_WIDTH 1900
#define BAMT_REFERENCE_RESOLUTION_HEIGHT 1100
#define BAMT_WORLD_SCALE 100

// RESOLUTION & FRAME RATE
#define BAMT_RESOLUTION_WIDTH 1280
#define BAMT_RESOLUTION_HEIGHT 720
#define BAMT_TARGET_FRAME_RATE 60

// PHYSICS
#define BAMT_PHYSICS_STEPS 50
#define BAMT_TIMESTEP_LIMIT 0.08f
#endif